/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vyashm;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author HOME
 */
public class feePayment extends javax.swing.JFrame {
Connection con;
String name;
float due_fee;
int s_no;
float fee_paid;
    /**
     * Creates new form feePayment
     */
    public feePayment() {
        initComponents();
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
			String jdbcurl="jdbc:oracle:thin:system/password//localhost:1521/xe";
		 con=DriverManager.getConnection(jdbcurl);  
        String sql="select s_no from student where check_out is null order by s_no";
        PreparedStatement st=con.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        
        while(rs.next())
        {
            Integer sno=(Integer)rs.getInt(1);
            int s_no=sno.intValue();
            sCombo.addItem(s_no);
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        feed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        feep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pick = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        room_fee = new javax.swing.JTextField();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Serial Number:");

        sCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Name:");

        sname.setEditable(false);

        jLabel3.setText("Room no:");

        roomno.setEditable(false);

        jLabel4.setText("Due Fee:");

        feed.setEditable(false);

        jLabel5.setText("Payment:");

        feep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                feepKeyTyped(evt);
            }
        });

        jLabel6.setText("Date:");

        jLabel7.setText("Fees:");

        room_fee.setEditable(false);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sname)
                            .addComponent(roomno)
                            .addComponent(feed)
                            .addComponent(feep)
                            .addComponent(pick, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(room_fee)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sname, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomno, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(room_fee, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pick, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sComboActionPerformed
        // TODO add your handling code here:
        Integer sno=(Integer)sCombo.getSelectedItem();
        s_no=sno.intValue();
        try{
            String sql="select name, room_no,fee_due from student where s_no=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setInt(1,s_no);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                name=rs.getString(1);
                sname.setText(name);
                String room_no=rs.getString(2);
                roomno.setText(room_no);
                String fee_due=rs.getString(3);
                feed.setText(fee_due);
                due_fee=rs.getFloat(3);
                
            }
            int room_no=Integer.parseInt(roomno.getText());
            pst=con.prepareStatement("select fee from rooms where room_no=?");
            pst.setInt(1,room_no);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String fee=rs.getString(1);
                room_fee.setText(fee);
            }
            
             
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_sComboActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
            
            float pay=Float.parseFloat(feep.getText());
            java.util.Date d=pick.getDate();
            java.sql.Date sqlDate = new java.sql.Date(d.getTime());
           PreparedStatement pst=con.prepareStatement("insert into fee_payment values(?,?,?,?)");
            pst.setInt(1, s_no);
            pst.setString(2,name);
            pst.setFloat(3,pay);
            pst.setDate(4,sqlDate);
            pst.executeUpdate();
            pst=con.prepareStatement("select fee_paid from student where s_no=?");
                 
                 pst.setInt(1, s_no);
                 ResultSet rs=pst.executeQuery();
                 if(rs.next())
                 {
                     fee_paid=rs.getFloat(1);
                 }
            JOptionPane.showMessageDialog(this,"Payment made successfully","Congrats",JOptionPane.PLAIN_MESSAGE);
             if(pay==due_fee)
             {
                 
                 
                float totalfee=pay+fee_paid;
                 due_fee=0;
                 pst=con.prepareStatement("update student set fee_due=? where s_no=?");
                 pst.setFloat(1, due_fee);
                 pst.setInt(2, s_no);
                 pst.executeUpdate();
                 pst=con.prepareStatement("update student set fee_paid=? where s_no=?");
                 pst.setFloat(1,totalfee);
                 pst.setInt(2, s_no);
                 pst.executeUpdate();
                 pst=con.prepareStatement("update student set check_in=? where s_no=?");
                 pst.setDate(1,sqlDate);
                 pst.setInt(2, s_no);
                 pst.executeUpdate();
             }
             else if(pay<due_fee)
             {
                 float totalfee=pay+fee_paid;
                 due_fee=due_fee-pay;
                 pst=con.prepareStatement("update student set fee_due=? where s_no=?");
                 pst.setFloat(1, due_fee);
                 pst.setInt(2, s_no);
                 pst.executeUpdate();
                 pst=con.prepareStatement("update student set fee_paid=? where s_no=?");
                 pst.setFloat(1,totalfee);
                 pst.setInt(2, s_no);
                 pst.executeUpdate();
                 pst=con.prepareStatement("update student set check_in=? where s_no=?");
                 pst.setDate(1,sqlDate);
                 pst.setInt(2, s_no);
                 pst.executeUpdate();
             }
             
             
                 
             
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void feepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feepKeyTyped
        // TODO add your handling code here:
        char letter=evt.getKeyChar();
        if(!(Character.isDigit(letter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_feepKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField feed;
    private javax.swing.JTextField feep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private org.jdesktop.swingx.JXDatePicker pick;
    private javax.swing.JTextField room_fee;
    private javax.swing.JTextField roomno;
    private javax.swing.JComboBox<Integer> sCombo;
    private javax.swing.JTextField sname;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
