/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vyashm;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.JOptionPane;
/**
 *
 * @author HOME
 */
public class onlineReg extends javax.swing.JFrame {
Connection con,con2;
int rno;
 String rtype;
 int n_sn;
 String pass="tomato02";
String uname="amisium098";
int delete_row;
String table_g;
String roomtype;
    /**
     * Creates new form onlineReg
     */
    public onlineReg() {
        initComponents();
        try{
       Class.forName("oracle.jdbc.driver.OracleDriver");
        String jdbcurl="jdbc:oracle:thin:system/password//localhost:1521/xe";
        con=DriverManager.getConnection(jdbcurl); 
        
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    public onlineReg(String name,int new_sno,int d_row, String table_g2,String rtype)
    {
        initComponents();
        sname.setText(name);
        n_sn=new_sno;
        delete_row=d_row;
        table_g=table_g2;
        if(rtype.equalsIgnoreCase("ac"))
        {
            roomtype=rtype;
        }
        else
        roomtype=rtype.toLowerCase();
        
        if(table_g.equalsIgnoreCase("male"))
        genText.setText("male");
        else
            genText.setText("female");
        try{
       Class.forName("oracle.jdbc.driver.OracleDriver");
        String jdbcurl="jdbc:oracle:thin:system/tomato02@//localhost:1521/xe";
        con=DriverManager.getConnection(jdbcurl); 
        /*String sql="select room_no from rooms where vacant!=0";
        PreparedStatement st=con.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        
        while(rs.next())
        {
            int r_no=rs.getInt(1);
            roomnoCombo.addItem(r_no);
        }*/
        genfn();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        roomnoCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        feep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pick = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        rFee = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        genText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        sname.setEditable(false);

        jLabel6.setText("Room No:");

        roomnoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Room Type:");

        rType.setEditable(false);

        jLabel3.setText("Payment:");

        feep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                feepKeyTyped(evt);
            }
        });

        jLabel4.setText("Date:");

        jLabel5.setText("Room Fee:");

        rFee.setEditable(false);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Gender:");

        genText.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(feep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pick, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(genText, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                        .addGap(78, 78, 78))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sname)
                                        .addComponent(roomnoCombo, 0, 125, Short.MAX_VALUE)
                                        .addComponent(rType)
                                        .addComponent(rFee))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(genText))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomnoCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rType, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rFee, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feep, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomnoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoComboActionPerformed
        // TODO add your handling code here:
        Integer r_no=(Integer)roomnoCombo.getSelectedItem();
        rno=r_no.intValue();
        try{
        PreparedStatement st=con.prepareStatement("select * from rooms where room_no=?");
        st.setInt(1, rno);
        ResultSet rs=st.executeQuery();
        if(rs.next())
        {
            rtype=rs.getString(2);
            rType.setText(rtype);
            String rfee=rs.getString(5);
            rFee.setText(rfee);
            
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_roomnoComboActionPerformed

    private void genfn() {                                       
        // TODO add your handling code here:
        try{
            String gendr=genText.getText();
            
           if(gendr.equalsIgnoreCase("male"))
            {
               /* if(roomnoCombo.getSelectedIndex()!=-1)
                {
                    //roomnoCombo.setSelectedIndex(-1);
                    roomnoCombo.removeAllItems();
                    
                }*/
        String sql="select room_no from rooms where build=? and r_type=? and vacant!=0";
        PreparedStatement st=con.prepareStatement(sql);
        st.setString(1, "build1");
        st.setString(2,roomtype);
        ResultSet rs=st.executeQuery();
        
        while(rs.next())
        {
            int r_no=rs.getInt(1);
            roomnoCombo.addItem(r_no);
        }
            }
            else
            {
                /*if(roomnoCombo.getSelectedIndex()!=-1)
                {
                    //roomnoCombo.setSelectedIndex(-1);
                    roomnoCombo.removeAllItems();
                }*/
                String sql="select room_no from rooms where build=? and r_type=? and vacant!=0";
        PreparedStatement st=con.prepareStatement(sql);
        st.setString(1, "build2");
        st.setString(2,roomtype);
        ResultSet rs=st.executeQuery();
        
        while(rs.next())
        {
            int r_no=rs.getInt(1);
            roomnoCombo.addItem(r_no);
        }
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }                               
    
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try{
            String name=sname.getText();
            int room_fee=Integer.parseInt(rFee.getText());
            float fee_p=Float.parseFloat(feep.getText());
            float fee_d=Float.parseFloat(rFee.getText())-fee_p;
            java.util.Date d=pick.getDate();
            java.sql.Date sqlDate = new java.sql.Date(d.getTime());
            //String gendr=(String)gender.getSelectedItem();
            PreparedStatement pst=con.prepareStatement("insert into student(room_no,name,r_type,fee_paid,fee_due,check_in,reg_type,gender) values(?,?,?,?,?,?,?,?)");
            pst.setInt(1, rno);
            pst.setString(2, name);
            pst.setString(3, rtype);
            pst.setFloat(4,fee_p);
            pst.setFloat(5, fee_d);
            pst.setDate(6,sqlDate );
            pst.setString(7, "yes");
            pst.setString(8, genText.getText());
            pst.executeUpdate();
            System.out.println("success1");
            
            
            con.close();
            Class.forName("com.mysql.jdbc.Driver");
            con2=DriverManager.getConnection("jdbc:mysql://mysql8.db4free.net:3307/vyas?useSSL=false",uname,pass);
            System.out.println("here2");
            pst=con2.prepareStatement("delete from new_student where s_no=?");
            pst.setInt(1,n_sn);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inserted Successfully","Congrats",JOptionPane.PLAIN_MESSAGE);
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void feepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feepKeyTyped
        // TODO add your handling code here:
        char letter=evt.getKeyChar();
        if(!(Character.isDigit(letter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_feepKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(onlineReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(onlineReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(onlineReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(onlineReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new onlineReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField feep;
    private javax.swing.JTextField genText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private org.jdesktop.swingx.JXDatePicker pick;
    private javax.swing.JTextField rFee;
    private javax.swing.JTextField rType;
    private javax.swing.JComboBox<Integer> roomnoCombo;
    private javax.swing.JTextField sname;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
