/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vyashm;

import java.awt.Color;

/**
 *
 * @author HOME
 */
public class studentMIDI extends javax.swing.JFrame {

    /**
     * Creates new form studentMIDI
     */
    public studentMIDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        onlinereg = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        left = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        listB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Student Details");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(180, 30, 200, 40);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setText("Offline Reg");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton1);
        jButton1.setBounds(60, 140, 140, 50);

        onlinereg.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        onlinereg.setText("Online Reg");
        onlinereg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onlineregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onlineregMouseExited(evt);
            }
        });
        onlinereg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineregActionPerformed(evt);
            }
        });
        desktopPane.add(onlinereg);
        onlinereg.setBounds(310, 140, 140, 50);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton3.setText("Boy's");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton3);
        jButton3.setBounds(60, 260, 140, 50);

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton4.setText("Girl's");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton4);
        jButton4.setBounds(310, 260, 140, 50);

        left.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        left.setText("Leaving");
        left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leftMouseExited(evt);
            }
        });
        left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftActionPerformed(evt);
            }
        });
        desktopPane.add(left);
        left.setBounds(60, 360, 140, 50);
        desktopPane.add(jSeparator1);
        jSeparator1.setBounds(60, 100, 390, 90);
        desktopPane.add(jSeparator2);
        jSeparator2.setBounds(60, 220, 390, 90);
        desktopPane.add(jSeparator4);
        jSeparator4.setBounds(60, 330, 390, 80);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Offline and Online Registration");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(60, 100, 220, 30);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("View List of students currently occupying rooms");
        desktopPane.add(jLabel3);
        jLabel3.setBounds(60, 224, 310, 20);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("Fill details for leaving students or view list of students who left hostel");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(60, 334, 440, 20);

        listB.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        listB.setText("View List");
        listB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listBMouseExited(evt);
            }
        });
        listB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBActionPerformed(evt);
            }
        });
        desktopPane.add(listB);
        listB.setBounds(310, 360, 140, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new studentDetails().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void onlineregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineregActionPerformed
        // TODO add your handling code here:
        newStudent frm=new newStudent();
        frm.setVisible(true);
    }//GEN-LAST:event_onlineregActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        viewStudentData frm= new viewStudentData("male");
                frm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        viewStudentData frm= new viewStudentData("female");
                frm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftActionPerformed
        // TODO add your handling code here:
        new leftStudent().setVisible(true);
    }//GEN-LAST:event_leftActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setForeground(Color.red);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton1MouseExited

    private void onlineregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineregMouseEntered
        // TODO add your handling code here:
        onlinereg.setForeground(Color.red);
    }//GEN-LAST:event_onlineregMouseEntered

    private void onlineregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineregMouseExited
        // TODO add your handling code here:
        onlinereg.setForeground(Color.BLACK);
    }//GEN-LAST:event_onlineregMouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setForeground(Color.red);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jButton4.setForeground(Color.red);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton4MouseExited

    private void leftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftMouseEntered
        // TODO add your handling code here:
        left.setForeground(Color.red);
    }//GEN-LAST:event_leftMouseEntered

    private void leftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftMouseExited
        // TODO add your handling code here:
        left.setForeground(Color.BLACK);
    }//GEN-LAST:event_leftMouseExited

    private void listBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBActionPerformed
        // TODO add your handling code here:
        new viewLeft().setVisible(true);
    }//GEN-LAST:event_listBActionPerformed

    private void listBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBMouseEntered
        // TODO add your handling code here:
        listB.setForeground(Color.red);
    }//GEN-LAST:event_listBMouseEntered

    private void listBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBMouseExited
        // TODO add your handling code here:
        listB.setForeground(Color.BLACK);
    }//GEN-LAST:event_listBMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentMIDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentMIDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentMIDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentMIDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentMIDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton left;
    private javax.swing.JButton listB;
    private javax.swing.JButton onlinereg;
    // End of variables declaration//GEN-END:variables

}
